# ----
# Site

title: sambaash
description: Jekyll template for API documentation.
url: https://harinidevi.github.io/
google_analytics_key:
permalink: pretty
theme: mytheme
baseurl: ""
github: https://github.com/HariniDevi/harinidevi.github.io/blob/master/
# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position: 1
  applications:
    title: Applications
    position: 2  
  api:
    title: APIs
    position: 3
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "applications"
    values:
      _hide_content: true    
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/style.css
